# Generated by Django 5.2 on 2025-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadvicerequest',
            name='problem_type',
            field=models.CharField(blank=True, help_text='Optional: Type of problem or topic user needs advice on.', max_length=255, null=True, verbose_name='Problem Type/Topic'),
        ),
    ]
