# Generated by Django 5.2 on 2025-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogadvicerequest_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: A featured image for the blog post. Will be shown in listings and at the top of the post.', null=True, upload_to='blog/images/%Y/%m/', verbose_name='Featured Image'),
        ),
    ]
