# Generated by Django 5.2 on 2025-04-17 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkillProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('attempts_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill Proficiency',
                'verbose_name_plural': 'User Skill Proficiencies',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
