# Generated by Django 5.2 on 2025-04-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_emergencymodesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestattempt',
            name='completion_points_awarded',
            field=models.BooleanField(default=False, help_text='Indicates if points for completing this test have been awarded.', verbose_name='completion points awarded'),
        ),
    ]
