# Generated by Django 5.2 on 2025-04-21 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_conversationsession_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionattempt',
            name='conversation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_attempts', to='study.conversationsession', verbose_name='conversation session'),
        ),
    ]
