# Generated by Django 5.2 on 2025-04-28 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('learning', '0003_skill_is_active'),
        ('study', '0007_alter_userskillproficiency_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userquestionattempt',
            index=models.Index(fields=['test_attempt', 'question'], name='study_userq_test_at_03eead_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['user', 'status'], name='study_usert_user_id_9729f5_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['user', 'attempt_type'], name='study_usert_user_id_f0b89c_idx'),
        ),
    ]
