# Generated by Django 5.2 on 2025-04-28 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('learning', '0003_skill_is_active'),
        ('study', '0008_userquestionattempt_study_userq_test_at_03eead_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestattempt',
            name='attempt_type',
            field=models.CharField(choices=[('level_assessment', 'Level Assessment'), ('practice', 'Practice Test'), ('simulation', 'Full Simulation'), ('traditional', 'Traditional Practice Session')], db_index=True, help_text='The specific type of this test attempt instance.', max_length=20, verbose_name='attempt type'),
        ),
        migrations.AddIndex(
            model_name='userquestionattempt',
            index=models.Index(fields=['user', 'mode'], name='study_userq_user_id_d2ed12_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionattempt',
            index=models.Index(fields=['user', 'question', 'is_correct'], name='study_userq_user_id_f1655b_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillproficiency',
            index=models.Index(fields=['user', 'proficiency_score'], name='study_users_user_id_39f53b_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestattempt',
            index=models.Index(fields=['user', 'start_time'], name='study_usert_user_id_019d7b_idx'),
        ),
    ]
