# Generated by Django 5.2 on 2025-04-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_alter_usertestattempt_attempt_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionattempt',
            name='used_solution_method',
        ),
        migrations.AddField(
            model_name='userquestionattempt',
            name='revealed_answer',
            field=models.BooleanField(default=False, help_text='Track if the user explicitly revealed the correct answer choice.', verbose_name='revealed correct answer'),
        ),
        migrations.AddField(
            model_name='userquestionattempt',
            name='revealed_explanation',
            field=models.BooleanField(default=False, help_text='Track if the user explicitly revealed the explanation.', verbose_name='revealed explanation'),
        ),
    ]
