# Generated by Django 5.2 on 2025-05-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_remove_userquestionattempt_unique_user_question_per_test_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestattempt',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('error', 'Error')], db_index=True, default='started', max_length=15, verbose_name='status'),
        ),
    ]
