# Generated by Django 5.2 on 2025-07-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_alter_usertestattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencymodesession',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='AI-generated feedback on session performance.'),
        ),
        migrations.AddField(
            model_name='emergencymodesession',
            name='overall_score',
            field=models.FloatField(blank=True, help_text='Overall score percentage.', null=True),
        ),
        migrations.AddField(
            model_name='emergencymodesession',
            name='quantitative_score',
            field=models.FloatField(blank=True, help_text='Quantitative section score percentage.', null=True),
        ),
        migrations.AddField(
            model_name='emergencymodesession',
            name='results_summary',
            field=models.JSONField(blank=True, help_text='Detailed breakdown of scores by subsection.', null=True),
        ),
        migrations.AddField(
            model_name='emergencymodesession',
            name='verbal_score',
            field=models.FloatField(blank=True, help_text='Verbal section score percentage.', null=True),
        ),
    ]
