# Generated by Django 5.2 on 2025-07-30 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_emergencymodesession_ai_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencymodesession',
            name='shared_with_admin',
        ),
        migrations.CreateModel(
            name='EmergencySupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('technical', 'Technical Issue'), ('academic', 'Academic Question'), ('content', 'Problem with a Question'), ('other', 'Other')], default='other', max_length=20, verbose_name='Problem Type')),
                ('description', models.TextField(help_text='Detailed description of the problem or question from the user.', verbose_name='Description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, help_text='The emergency session during which the request was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='study.emergencymodesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Support Request',
                'verbose_name_plural': 'Emergency Support Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
