# Generated by Django 5.2 on 2025-07-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_remove_emergencymodesession_shared_with_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencymodesession',
            name='days_until_test',
            field=models.IntegerField(blank=True, help_text="Number of days until the user's test, as stated at session start.", null=True),
        ),
    ]
