# Generated by Django 5.2 on 2025-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='issue_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('financial', 'Financial'), ('question_problem', 'Problem with a question'), ('suggestion', 'Suggestion'), ('inquiry', 'General Inquiry'), ('other', 'Other')], db_index=True, max_length=20, verbose_name='Issue Type'),
        ),
    ]
