# Generated by Django 5.2 on 2025-06-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_supportticket_issue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique identifier for the issue type (e.g., 'technical').", max_length=100, unique=True, verbose_name='Name')),
                ('display_name', models.CharField(help_text="The user-facing name (e.g., 'Technical').", max_length=255, verbose_name='Display Name')),
            ],
            options={
                'verbose_name': 'Issue Type',
                'verbose_name_plural': 'Issue Types',
                'ordering': ['display_name'],
            },
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='issue_types',
            field=models.ManyToManyField(related_name='support_tickets', to='support.issuetype', verbose_name='Issue Types'),
        ),
    ]
