# Generated by Django 5.2 on 2025-06-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_issuetype_remove_supportticket_issue_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='issue_types',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='issue_type',
            field=models.CharField(blank=True, choices=[('technical', 'Technical'), ('question_problem', 'Problem with a question'), ('suggestion', 'Suggestion'), ('inquiry', 'General Inquiry'), ('other', 'Other')], db_index=True, max_length=20, null=True, verbose_name='Issue Type'),
        ),
    ]
