# Generated by Django 5.2 on 2025-07-04 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_structured',
            field=models.JSONField(blank=True, help_text="Key-value JSON for template-based pages. E.g., {'hero_title': {'value': '...'}}", null=True, verbose_name='Structured Content (Template-based)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='homepagefeaturecard',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='homepagefeaturecard',
            name='svg_image',
            field=models.TextField(blank=True, null=True, verbose_name='SVG Image Code'),
        ),
        migrations.AlterField(
            model_name='homepagefeaturecard',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='homepagestatistic',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='homepagestatistic',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, help_text="For simple HTML content. Use 'Structured Content' for modern, template-based pages.", verbose_name='Content (Simple/Legacy)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text="Unique identifier for the page/content (e.g., 'our-story'). Used in URLs.", max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='partnercategory',
            name='google_form_link',
            field=models.URLField(max_length=500, verbose_name='Google Form Link'),
        ),
        migrations.AlterField(
            model_name='partnercategory',
            name='icon_svg_or_class',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon SVG or Class'),
        ),
        migrations.AlterField(
            model_name='partnercategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(blank=True, help_text="A unique identifier for the image (e.g., 'our-story-hero'). Auto-generated if left blank.", max_length=100, unique=True, verbose_name='Image Slug')),
                ('name', models.CharField(help_text="An internal name for organizing images (e.g., 'Our Story Hero Image').", max_length=255, verbose_name='Image Name')),
                ('image', models.ImageField(help_text='Upload the image file.', upload_to='content_images/%Y/%m/', verbose_name='Image File')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for accessibility (SEO).', max_length=255, verbose_name='Alt Text')),
                ('page', models.ForeignKey(blank=True, help_text='The page this image is primarily used on. Leave blank for general use.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.page', verbose_name='Associated Page')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Image',
                'verbose_name_plural': 'Content Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
