# Generated by Django 5.2 on 2025-07-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, help_text="For simple HTML content. Use 'Structured Content' for modern, template-based pages.", null=True, verbose_name='Content (Simple/Legacy)'),
        ),
    ]
