# Generated by Django 5.2 on 2025-07-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload the image file.', null=True, upload_to='content_images/%Y/%m/', verbose_name='Image File'),
        ),
    ]
