# Generated by Django 5.2 on 2025-07-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_contentimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercategory',
            name='icon_svg_or_class',
        ),
        migrations.AddField(
            model_name='partnercategory',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload an icon image for the partner category (e.g., 70x70 pixels).', null=True, upload_to='partner_icons/', verbose_name='Icon Image'),
        ),
    ]
