# Generated by Django 5.2 on 2025-05-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SYSTEM', 'System Update'), ('USER_PROFILE', 'User Profile Update'), ('SUBSCRIPTION', 'Subscription Update'), ('BADGE_EARNED', 'Badge Earned'), ('COMMUNITY_POST', 'Community Post Interaction'), ('COMMUNITY_REPLY', 'Community Reply Interaction'), ('CHALLENGE_INVITE', 'Challenge Invitation'), ('CHALLENGE_UPDATE', 'Challenge Update'), ('MENTOR_ASSIGNMENT', 'Mentor Assignment'), ('SUPPORT_TICKET', 'Support Ticket Update'), ('CHAT', 'Chat Message')], db_index=True, default='INFO', max_length=20, verbose_name='Notification Type'),
        ),
    ]
