# Generated by Django 5.2 on 2025-04-13 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('duration_days', models.IntegerField(default=30, help_text='Subscription length in days granted by this code.')),
                ('is_active', models.BooleanField(default=True, help_text='Can this code be used?')),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Has this code already been redeemed?')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about the code.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who generated the code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('has_taken_qiyas_before', models.BooleanField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('sub_admin', 'Sub-Admin')], db_index=True, default='student', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('last_study_activity_at', models.DateTimeField(blank=True, null=True)),
                ('current_level_verbal', models.FloatField(blank=True, null=True)),
                ('current_level_quantitative', models.FloatField(blank=True, null=True)),
                ('last_visited_study_option', models.CharField(blank=True, max_length=100, null=True)),
                ('dark_mode_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10)),
                ('dark_mode_auto_enabled', models.BooleanField(default=False)),
                ('dark_mode_auto_time_start', models.TimeField(blank=True, null=True)),
                ('dark_mode_auto_time_end', models.TimeField(blank=True, null=True)),
                ('notify_reminders_enabled', models.BooleanField(default=True)),
                ('upcoming_test_date', models.DateField(blank=True, null=True)),
                ('study_reminder_time', models.TimeField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('serial_code_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='users.serialcode')),
            ],
        ),
    ]
