# Generated by Django 5.2 on 2025-04-25 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_serialcode_subscription_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='serialcode',
            name='code',
            field=models.CharField(db_index=True, help_text='The unique serial code string (case-insensitive).', max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='serialcode',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Subscription length in days granted by this code. Used for calculating expiry.', verbose_name='Duration (Days)'),
        ),
        migrations.AlterField(
            model_name='serialcode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the code can currently be used for redemption.', verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='serialcode',
            name='notes',
            field=models.TextField(blank=True, help_text='Administrative notes (e.g., batch identifier, purpose).', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='serialcode',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('1_month', '1 Month'), ('6_months', '6 Months'), ('12_months', '12 Months'), ('custom', 'Custom Duration')], db_index=True, help_text='Categorizes the intended duration or type of the code.', max_length=20, null=True, verbose_name='Subscription Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Profile Created At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_level_quantitative',
            field=models.FloatField(blank=True, help_text='Assessed proficiency level (0-100) in the Quantitative section.', null=True, verbose_name='Current Quantitative Level (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_level_verbal',
            field=models.FloatField(blank=True, help_text='Assessed proficiency level (0-100) in the Verbal section.', null=True, verbose_name='Current Verbal Level (%)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_streak_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Study Streak (Days)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(help_text="User's full legal name.", max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, help_text='Educational level (e.g., Grade 12, University Freshman).', max_length=100, null=True, verbose_name='Grade/Level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_study_activity_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last tracked study action for streak calculation.', null=True, verbose_name='Last Study Activity At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_visited_study_option',
            field=models.CharField(blank=True, help_text="Slug identifier of the last viewed section in 'Study Page'.", max_length=100, null=True, verbose_name='Last Visited Study Option Slug'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longest_streak_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Longest Study Streak (Days)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='How the user prefers to be called.', max_length=100, null=True, verbose_name='Preferred Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='The user whose referral code this user signed up with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Referred By User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='serial_code_used',
            field=models.ForeignKey(blank=True, help_text='The last serial code used to activate/extend subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_profiles', to='users.serialcode', verbose_name='Last Redeemed Serial Code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='study_reminder_time',
            field=models.TimeField(blank=True, help_text='Preferred time of day for study reminders (HH:MM).', null=True, verbose_name='Study Reminder Time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Profile Updated At'),
        ),
    ]
