# Generated by Django 5.2 on 2025-04-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('users', '0004_alter_userprofile_options_alter_serialcode_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions granted to this sub-admin user.', related_name='sub_admins', to='admin_panel.adminpermission', verbose_name='Admin Permissions'),
        ),
    ]
