# Generated by Django 5.2 on 2025-04-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_serialcode_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('SUBSCRIBED', 'Subscribed')], db_index=True, default='FREE_TRIAL', help_text="Indicates the user's current subscription level (e.g., Free Trial, Subscribed).", max_length=20, verbose_name='Account Type'),
        ),
    ]
