# Generated by Django 5.2 on 2025-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en-us', help_text="User's preferred language for emails and interface elements.", max_length=5, verbose_name='Preferred Language'),
        ),
    ]
