# Generated by Django 5.2 on 2025-05-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', help_text="User's preferred language for emails and interface elements.", max_length=5, verbose_name='Preferred Language'),
        ),
    ]
