# Generated by Django 5.2 on 2025-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('trainer', 'Trainer'), ('admin', 'Admin'), ('sub_admin', 'Sub-Admin')], db_index=True, default='student', max_length=20, verbose_name='Role'),
        ),
    ]
