# Generated by Django 5.2 on 2025-05-19 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_assigned_mentor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code_hash', models.CharField(help_text='Hashed version of the OTP code.', max_length=128, verbose_name='OTP Code (Hashed)')),
                ('otp_created_at', models.DateTimeField(auto_now_add=True, verbose_name='OTP Created At')),
                ('otp_expires_at', models.DateTimeField(verbose_name='OTP Expires At')),
                ('reset_token_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True, verbose_name='Reset Token (Hashed)')),
                ('reset_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Reset Token Expires At')),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='True if password has been successfully reset using this record.', verbose_name='Is Used?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Password Reset OTP & Token',
                'verbose_name_plural': 'Password Reset OTPs & Tokens',
                'ordering': ['-otp_created_at'],
            },
        ),
    ]
