# Generated by Django 5.2 on 2025-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('SUBSCRIBED', 'Subscribed'), ('PERMANENT', 'Permanent Access')], db_index=True, default='FREE_TRIAL', help_text="Indicates the user's current subscription level (e.g., Free Trial, Subscribed).", max_length=20, verbose_name='Account Type'),
        ),
    ]
