# Generated by Django 5.2 on 2025-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short description or biography about the user.', null=True, verbose_name='Bio / Description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook Profile URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram Profile URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Profile URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='X/Twitter Profile URL'),
        ),
    ]
