# Generated by Django 5.2 on 2025-07-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_bio_userprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('primary_1', 'أولى ابتدائي'), ('primary_2', 'ثانية ابتدائي'), ('primary_3', 'ثالثة ابتدائي'), ('primary_4', 'رابعة ابتدائي'), ('primary_5', 'خامسة ابتدائي'), ('primary_6', 'سادسة ابتدائي'), ('middle_1', 'أولى متوسط'), ('middle_2', 'ثانية متوسط'), ('middle_3', 'ثالثة متوسط'), ('high_1', 'أولى ثانوي'), ('high_2', 'ثانية ثانوي'), ('high_3', 'ثالث ثانوي'), ('uni_prep', 'سنة تحضيرية جامعة'), ('uni_student', 'طالب جامعي'), ('graduate', 'خريج'), ('other', 'أخرى')], help_text='Educational level (e.g., Grade 12, University Freshman).', max_length=100, null=True, verbose_name='Grade/Level'),
        ),
    ]
