from django.urls import path, include
from rest_framework.routers import DefaultRouter

from ..views import user_management as views

# Create a router instance specific to user management
router = DefaultRouter()
router.register(r"users", views.AdminUserViewSet, basename="admin-user")
router.register(r"sub-admins", views.AdminSubAdminViewSet, basename="admin-sub-admin")

# Define urlpatterns for this module
urlpatterns = [
    # Include URLs generated by the router (e.g., /users/, /users/{pk}/, /sub-admins/, etc.)
    path("", include(router.urls)),
    # Add custom action routes specific to user management
    path(
        "users/<int:user_id>/reset-password/",
        views.AdminPasswordResetView.as_view(),
        name="admin-user-reset-password",
    ),
    path(
        "users/<int:user_id>/adjust-points/",
        views.AdminPointAdjustmentView.as_view(),
        name="admin-user-adjust-points",
    ),
    # Example placeholder for future permission listing endpoint
    # path("permissions/", views.PermissionListView.as_view(), name="admin-permission-list"),
]
