from django.urls import path, include
from rest_framework.routers import DefaultRouter

from ..views import user_management as views
from ..views import user_detail_views

# Create a router instance specific to user management
router = DefaultRouter()
# Allow update/partial_update/destroy on AdminUserViewSet
router.register(r"users", views.AdminUserViewSet, basename="admin-user")

# Define urlpatterns for this module
urlpatterns = [
    # Include URLs generated by the router (e.g., /users/, /users/{pk}/, /sub-admins/, etc.)
    path("", include(router.urls)),
    # Add custom action routes specific to user management
    # Renamed AdminPasswordResetView to clarify it uses user_id from URL
    path(
        "users/<int:user_id>/reset-password/",
        views.AdminPasswordResetView.as_view(),
        name="admin-user-reset-password",
    ),
    path(
        "users/<int:user_id>/adjust-points/",
        views.AdminPointAdjustmentView.as_view(),
        name="admin-user-adjust-points",
    ),
    # Endpoint to list available permissions
    path(
        "permissions/", views.PermissionListView.as_view(), name="admin-permission-list"
    ),
    path(
        "users/<int:user_id>/statistics/",
        user_detail_views.AdminUserStatisticsView.as_view(),
        name="admin-user-statistics",
    ),
    path(
        "users/<int:user_id>/test-history/",
        user_detail_views.AdminUserTestHistoryView.as_view(),
        name="admin-user-test-history",
    ),
    path(
        "users/<int:user_id>/point-log/",
        user_detail_views.AdminUserPointLogView.as_view(),
        name="admin-user-point-log",
    ),
]
