# Generated by Django 5.2 on 2025-04-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningsection',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the learning section.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='learningsection',
            name='name',
            field=models.CharField(help_text='The primary name of the learning section (e.g., Verbal Section).', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='learningsection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines the display order in lists (lower numbers appear first).', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='learningsection',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (leave blank to auto-generate from name).', max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='learningsubsection',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the learning sub-section.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='learningsubsection',
            name='name',
            field=models.CharField(help_text='The name of the sub-section (e.g., Reading Comprehension).', max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='learningsubsection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines the display order within its parent section (lower numbers first).', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='learningsubsection',
            name='section',
            field=models.ForeignKey(help_text='The parent Learning Section this sub-section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='learning.learningsection', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='learningsubsection',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (leave blank to auto-generate from section and name).', max_length=170, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='The letter corresponding to the correct option.', max_length=1, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], db_index=True, default=3, help_text='Estimated difficulty level of the question.', verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed step-by-step explanation for the solution (supports Markdown/HTML).', null=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='A small hint to guide the student without giving away the answer.', null=True, verbose_name='Hint'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck this to hide the question from students without deleting it.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='The main text or problem statement of the question.', verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(blank=True, help_text='The main skill tested by this question (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.skill', verbose_name='Primary Skill'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution_method_summary',
            field=models.TextField(blank=True, help_text='A brief summary of the general strategy or method to solve the question.', null=True, verbose_name='Solution Method Summary'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subsection',
            field=models.ForeignKey(help_text='The primary sub-section this question belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='learning.learningsubsection', verbose_name='Sub-Section'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the skill.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='The name of the specific skill (e.g., Solving Linear Equations).', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (leave blank to auto-generate from subsection and name).', max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='subsection',
            field=models.ForeignKey(help_text='The parent Learning Sub-Section this skill belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='learning.learningsubsection', verbose_name='Sub-Section'),
        ),
    ]
