# Generated by Django 5.2 on 2025-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_learningsection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this skill is active and should be used in question selections, filters, etc.', verbose_name='Active Status'),
        ),
    ]
