# Generated by Django 5.2 on 2025-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_skill_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsubsection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this sub-section is active and should be used in question selections, filters, etc.', verbose_name='Active Status'),
        ),
    ]
