# Generated by Django 5.2 on 2025-07-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learningsubsection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image to accompany the question text.', null=True, upload_to='questions/images/', verbose_name='Image'),
        ),
    ]
