# Generated by Django 5.2 on 2025-09-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The primary name of the test type (e.g., General Aptitude).', max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (leave blank to auto-generate from name).', max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Optional description of the test type.', null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon')], db_index=True, default='active', help_text="Controls visibility for users ('Coming Soon' or 'Active').", max_length=20, verbose_name='Status')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the display order in lists.', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Test Type',
                'verbose_name_plural': 'Test Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='learningsection',
            options={'ordering': ['test_type__order', 'order', 'name'], 'verbose_name': 'Learning Section', 'verbose_name_plural': 'Learning Sections'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['section__order', 'subsection__order', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='article_content',
            field=models.TextField(blank=True, null=True, verbose_name='Article/Passage Content'),
        ),
        migrations.AddField(
            model_name='question',
            name='article_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Article Title'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='questions/audio/', verbose_name='Audio File'),
        ),
        migrations.AddField(
            model_name='skill',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The parent Learning Section this skill belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='learning.learningsection', verbose_name='Parent Section'),
        ),
        migrations.AlterField(
            model_name='learningsection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='learningsection',
            name='name',
            field=models.CharField(help_text='e.g., Verbal Section', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='learningsection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='learningsection',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.skill', verbose_name='Primary Skill'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='learning.learningsubsection', verbose_name='Sub-Section'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='subsection',
            field=models.ForeignKey(blank=True, help_text="Optionally refine the skill's category to a sub-section.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='learning.learningsubsection', verbose_name='Sub-Section (Optional)'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('section', 'subsection', 'name')},
        ),
        migrations.AddField(
            model_name='learningsection',
            name='test_type',
            field=models.ForeignKey(blank=True, help_text='The parent Test Type this section belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_sections', to='learning.testtype', verbose_name='Test Type'),
        ),
        migrations.AlterUniqueTogether(
            name='learningsection',
            unique_together={('test_type', 'name')},
        ),
    ]
