# Generated by Django 5.2 on 2025-09-05 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_testtype_alter_learningsection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The unique title of the article or passage.', max_length=255, unique=True, verbose_name='Title')),
                ('content', models.TextField(help_text='The full text content of the article.', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="A descriptive name for internal use (e.g., 'Pythagorean Theorem Diagram').", max_length=200, verbose_name='Title/Name')),
                ('file', models.FileField(help_text='The actual uploaded image, audio, or video file.', upload_to='media_library/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], help_text='The type of media file, used by the frontend for rendering.', max_length=10, verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='article_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='article_title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Link to an article from the library. Leave blank if not needed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.article', verbose_name='Article/Passage'),
        ),
        migrations.AddField(
            model_name='question',
            name='media_content',
            field=models.ForeignKey(blank=True, help_text='Link to a media file from the library. Leave blank if not needed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.mediafile', verbose_name='Media Content (Image/Audio/Video)'),
        ),
    ]
