# Generated by Django 5.2 on 2025-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_article_mediafile_remove_question_article_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['subsection', 'id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='skill',
        ),
        migrations.AddField(
            model_name='question',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='The skills tested by this question.', related_name='questions', to='learning.skill', verbose_name='Skills'),
        ),
    ]
