from django.urls import path, include
from rest_framework.routers import DefaultRouter

from apps.community.api import views
from apps.community.api.reply_views import CommunityReplyLikeToggleView

app_name = "community"

router = DefaultRouter()
# Register the ViewSet for posts
# Provides URLs like: /posts/, /posts/{pk}/
router.register(
    r"posts",
    views.CommunityPostViewSet,
    basename="communitypost",  # Base name for URL reversing
)

urlpatterns = [
    # Include URLs generated by the router
    path("", include(router.urls)),
    # Custom URL for listing/creating replies for a specific post
    # Example: /posts/123/replies/
    path(
        "posts/<int:post_pk>/replies/",
        views.CommunityReplyListCreateView.as_view(),
        name="post-replies-list-create",  # Descriptive name
    ),
    path(
        "replies/<int:reply_pk>/toggle_like/",
        CommunityReplyLikeToggleView.as_view(),
        name="reply-toggle-like",
    ),
    # Custom URL for listing tags
    # Example: /tags/
    path(
        "tags/",
        views.TagListView.as_view(),
        name="tag-list",
    ),
    # --- Potential Future URLs ---
    # Maybe add URLs for managing replies individually? (Less common for forum replies)
    # path(
    #     "replies/<int:pk>/",
    #     views.CommunityReplyDetailView.as_view(), # Needs a new DetailView
    #     name="reply-detail",
    # ),
]
