# Generated by Django 5.2 on 2025-04-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier for the permission (e.g., 'view_users', 'manage_content').", unique=True, verbose_name='Slug')),
                ('name', models.CharField(help_text='Human-readable name for the permission.', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of what this permission allows.', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Admin Permission',
                'verbose_name_plural': 'Admin Permissions',
                'ordering': ['name'],
            },
        ),
    ]
