# Generated by Django 5.2 on 2025-08-02 16:41

import apps.admin_panel.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel (XLSX)')], max_length=10, verbose_name='File Format')),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='The ID of the background task processing this job.', max_length=255, null=True, verbose_name='Celery Task ID')),
                ('filters', models.JSONField(default=dict, help_text='The query parameters used for this export.', verbose_name='Applied Filters')),
                ('file', models.FileField(blank=True, help_text='The final generated file.', null=True, upload_to=apps.admin_panel.models.export_file_path, verbose_name='Exported File')),
                ('error_message', models.TextField(blank=True, help_text='Details of the error if the job failed.', null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('requesting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Requesting User')),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
