# Generated by Django 5.2 on 2025-08-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_exportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='job_type',
            field=models.CharField(choices=[('TEST_ATTEMPTS', 'Test Attempts Export'), ('USERS', 'User Data Export')], default='TEST_ATTEMPTS', max_length=20, verbose_name='Job Type'),
        ),
    ]
