# Generated by Django 5.2 on 2025-09-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_exportjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='job_type',
            field=models.CharField(choices=[('TEST_ATTEMPTS', 'Test Attempts Export'), ('USERS', 'User Data Export'), ('QUESTIONS', 'Questions Export')], default='TEST_ATTEMPTS', max_length=20, verbose_name='Job Type'),
        ),
    ]
