import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic, Harmattan } from 'next/font/google';
import "./globals.css";
import Footer from "../components/public/Footer/page";
import Navbar from "../components/public/Navbar/page";


import { ThemeProvider } from '../components/ui/theme-provider';

const ibm = IBM_Plex_Sans_Arabic({ subsets: ['arabic'], weight: ['400', '700'], variable: '--font-body' });
const harmattan = Harmattan({ subsets: ['arabic'], weight: ['400', '700'], variable: '--font-heading' });

export const metadata: Metadata = {
  title: "ََQader",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" suppressHydrationWarning>
      <body
        className={`${ibm.variable} ${harmattan.variable}`}
        dir="rtl"
      >
        <ThemeProvider
          attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
        >
          <Navbar/>
          {children}
          <Footer/>
          </ThemeProvider>
      </body>
    </html>
  );
}
