# Generated by Django 5.2 on 2025-04-25 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon_class_or_image',
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload an image file for the badge icon.', null=True, upload_to='badges/icons/', verbose_name='Icon Image'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='criteria_description',
            field=models.TextField(help_text='User-facing text explaining how to earn the badge.', verbose_name='Criteria Description'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive badges cannot be earned.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='slug',
            field=models.SlugField(help_text='Unique identifier used internally and potentially in URLs.', max_length=110, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable explanation, especially for OTHER or specific contexts.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Related Object ID'),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='reason_code',
            field=models.CharField(choices=[('QUESTION_SOLVED', 'Question Solved'), ('TEST_COMPLETED', 'Test Completed'), ('LEVEL_ASSESSMENT_COMPLETED', 'Level Assessment Completed'), ('STREAK_BONUS', 'Streak Bonus'), ('FEATURE_FIRST_USE', 'Feature First Use'), ('CHALLENGE_PARTICIPATION', 'Challenge Participation'), ('CHALLENGE_WIN', 'Challenge Win'), ('REWARD_PURCHASE', 'Reward Purchase'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('REFERRAL_BONUS', 'Referral Bonus'), ('BADGE_EARNED', 'Badge Earned'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='Standardized code indicating the reason for the point change.', max_length=50, verbose_name='Reason Code'),
        ),
        migrations.AlterField(
            model_name='rewardstoreitem',
            name='asset_url_or_data',
            field=models.CharField(blank=True, help_text='Path to file, theme identifier, or other relevant data for the reward.', max_length=255, null=True, verbose_name='Asset URL or Data'),
        ),
        migrations.AlterField(
            model_name='rewardstoreitem',
            name='item_type',
            field=models.CharField(choices=[('avatar', 'Avatar/Theme'), ('material', 'Study Material/Outline'), ('competition_entry', 'Competition Entry'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='Item Type'),
        ),
        migrations.AddIndex(
            model_name='pointlog',
            index=models.Index(fields=['content_type', 'object_id'], name='gamificatio_content_4b865f_idx'),
        ),
    ]
