# Generated by Django 5.2 on 2025-04-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_badge_icon_class_or_image_badge_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardstoreitem',
            name='asset_url_or_data',
        ),
        migrations.AddField(
            model_name='rewardstoreitem',
            name='asset_file',
            field=models.FileField(blank=True, help_text='Optional downloadable file associated with the reward (e.g., PDF outline).', null=True, upload_to='rewards/assets/', verbose_name='Asset File'),
        ),
        migrations.AddField(
            model_name='rewardstoreitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional visual representation of the reward item.', null=True, upload_to='rewards/images/', verbose_name='Item Image'),
        ),
    ]
