# Generated by Django 5.2 on 2025-05-04 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_remove_rewardstoreitem_asset_url_or_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(db_index=True, help_text='The calendar date (UTC) of the study activity.', verbose_name='Study Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Logged At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_days', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Study Day Log',
                'verbose_name_plural': 'Study Day Logs',
                'ordering': ['-study_date'],
                'indexes': [models.Index(fields=['user', 'study_date'], name='gamificatio_user_id_71e59a_idx')],
                'unique_together': {('user', 'study_date')},
            },
        ),
    ]
