# Generated by Django 5.2 on 2025-05-04 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_studydaylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(blank=True, choices=[('STUDY_STREAK', 'Consecutive Study Days'), ('QUESTIONS_SOLVED', 'Correct Questions Solved'), ('TESTS_COMPLETED', 'Tests Completed (Any Type)'), ('OTHER', 'Other / Manual Award')], db_index=True, help_text='The type of condition required to earn this badge.', max_length=50, null=True, verbose_name='Criteria Type'),
        ),
        migrations.AddField(
            model_name='badge',
            name='target_value',
            field=models.PositiveIntegerField(blank=True, help_text="The numerical goal for the criteria (e.g., 5 for a 5-day streak, 50 for 50 questions). Not used for 'Other' type.", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Target Value'),
        ),
    ]
