# Generated by Django 5.2 on 2025-05-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_badge_criteria_type_badge_target_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(choices=[('STUDY_STREAK', 'Consecutive Study Days'), ('QUESTIONS_SOLVED', 'Correct Questions Solved'), ('TESTS_COMPLETED', 'Tests Completed (Any Type)'), ('OTHER', 'Other / Manual Award')], db_index=True, help_text='The type of condition required to earn this badge.', max_length=50, verbose_name='Criteria Type'),
        ),
    ]
