# Generated by Django 5.2 on 2025-05-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_alter_badge_criteria_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(choices=[('STUDY_STREAK', 'Consecutive Study Days'), ('QUESTIONS_SOLVED', 'Correct Questions Solved'), ('TESTS_COMPLETED', 'Tests Completed (Any Type)'), ('CHALLENGES_WON', 'Challenges Won'), ('OTHER', 'Other / Manual Award')], db_index=True, help_text='The type of condition required to earn this badge.', max_length=50, verbose_name='Criteria Type'),
        ),
    ]
