# Generated by Django 5.2 on 2025-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_alter_badge_criteria_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardstoreitem',
            name='code_name',
            field=models.SlugField(blank=True, help_text='A unique code name for the frontend to identify and unlock specific features. Leave blank if not applicable.', null=True, unique=True, verbose_name='Code Name'),
        ),
    ]
