# Generated by Django 5.2 on 2025-07-09 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communitypost_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attached to the post.', null=True, upload_to='community/posts/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_community_posts', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='communityreply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_community_replies', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
    ]
